### ISSUE TITLE
Rename initData property

### ISSUE THREAD

**Issue by yashha** [ChangJoo-Park/vue-editor-js#10]
Rename initData property to data. Sounds better, when we are able to edit dynamically it.

Breaking change, or we deprecate initData.

**Comment by ChangJoo-Park** [comment]
Good idea, I think initData is not represent a property. It is confusing name.
but remain the `initData` for the next version for backwards compatibility.  Just sync data and initData.

How about this?

**Comment by yashha** [comment]
Sounds good to me.

**Comment by ChangJoo-Park** [comment]
Using data in config with ^2.0.0
