### ISSUE TITLE
Toolbar Customization

### ISSUE THREAD

**Issue by orhanmusellim** [ChangJoo-Park/vue-editor-js#13]
How to remove in toolbar img or other selection ?

**Comment by yashha** [comment]
I guess it is not possible at the moment.
It should probably be overwritten by the customTools property in the future.

**Comment by yashha** [comment]
No I guess you can pass 
:image="false"
as prop.

or other props https://github.com/ChangJoo-Park/vue-editor-js/blob/master/src/Editor.vue#L59

**Comment by orhanmusellim** [comment]
Thanks 👍🏼

**Comment by ChangJoo-Park** [comment]
Thanks @yashha :)
