### ISSUE TITLE
New version of editor.js

### ISSUE THREAD

**Issue by milanP96** [ChangJoo-Park/vue-editor-js#17]
Hi @ChangJoo-Park. Can you change version in your package.json to last one?https://github.com/codex-team/editor.js/blob/master/docs/CHANGELOG.md

Currently in your package.json is 2.12.3, last one is 2.15.0

**Comment by ChangJoo-Park** [comment]
@milanP96 It is OK. `^2.12.3` will be download version 2.15.0 from npm :)

**Comment by milanP96** [comment]
Ok, but I am not see features of last version of editor.js

**Comment by ChangJoo-Park** [comment]
if you use this plugin, you must update your node_modules `rm -rf node_modules && npm install` or `npm update`

**Comment by milanP96** [comment]
After that, this is still old editor

**Comment by ChangJoo-Park** [comment]
I release vue-editor-js 0.4.0 please test this version.

@milanP96  Thanks for report issue 👍
