### ISSUE TITLE
vue-editor-js on Nuxt.js

### ISSUE THREAD

**Issue by milanP96** [ChangJoo-Park/vue-editor-js#2]
Hi. Do you know why the package works on a regular Vue.js project but does not work on th Nuxt.js. 
On image on google drive you can see settings for Vue.js(left part of screen) and for Nuxt.js(right)
[https://drive.google.com/file/d/1gpCcugo01RR8GRpyjiNrFXPHQTLy9S4_/view?usp=sharing](url)

**Comment by VladimirLevadnij** [comment]
Hello! It's also up to me, I also fail. Has anyone managed to include editor.js in Nuxt.js? Please tell me how did you do that :-)

**Comment by ChangJoo-Park** [comment]
I'll try it. I use Nuxt.js in product now. It is serious problemn for me :persevere:

**Comment by milanP96** [comment]
I did not notice your answer because I wrote a letter and sent you an
email. Thank you in any case

pet, 05. apr 2019. 15:29 ChangJoo Park(박창주) <notifications@github.com> je
napisao/la:

**Comment by ChangJoo-Park** [comment]
@milanP96 Please see this repo.
It may be you have typo in plugins path.

<img width="574" alt="2019-04-05 (2)" src="https://user-images.githubusercontent.com/1451365/55635950-d3e6bc80-57fc-11e9-83ee-a57abf9844f2.png">


https://github.com/ChangJoo-Park/vue-editor-on-nuxt/blob/master/nuxt.config.js#L37
https://github.com/ChangJoo-Park/vue-editor-on-nuxt/blob/master/plugins/vue-editor.js
https://github.com/ChangJoo-Park/vue-editor-on-nuxt/blob/master/pages/index.vue#L5

**Comment by ChangJoo-Park** [comment]
@VladimirLevadnij  please check this comment too.

If you fail again, please send me a link with failed repo. :sob: I challenge it

**Comment by milanP96** [comment]
It works now. I forgot one slash in nuxt.config.js. Thanks!

pet, 05. apr 2019. 16:48 ChangJoo Park(박창주) <notifications@github.com> je
napisao/la:

**Comment by milanP96** [comment]
But it works now and with my old code. I don't understand why :)

pet, 05. apr 2019. 21:52 Milan Petkovic <milan96petkovic@gmail.com> je
napisao/la:

**Comment by VladimirLevadnij** [comment]
@ChangJoo-Park Thanks! It works for me too now. In my case it was some problem with npx. Anyway I'm glad to meet you. You're doing a useful job for many people! :-)

**Comment by aslero** [comment]
`npm WARN tsutils@3.20.0 requires a peer of typescript@>=2.8.0 || >= 3.2.0-dev || >= 3.3.0-dev || >= 3.4.0-dev || >= 3.5.0-dev || >= 3.6.0-dev || >= 3.6.0-beta || >= 3.7.0-dev || >= 3.7.0-beta but none is installed. You must install peer dependencies yourself.`
