### ISSUE TITLE
Select text inlineToolbar not showing up 'Bold' or 'Italic' in Nuxt.

### ISSUE THREAD

**Issue by steven0811** [ChangJoo-Park/vue-editor-js#21]
I'm trying load all plugin in Nuxt (ex. header ...), and add some config in separate plugin config, It's still not showing up bold and italic tools in  inlineToolbar. I'm not for sure what am I doing wrong, and not sure about this problem will appear in Vue.

![Screen Shot 2019-08-26 at 1 52 50 AM](https://user-images.githubusercontent.com/4948562/63653825-6dab0800-c7a4-11e9-995b-e7856642efd2.png)

**Comment by Dylan-8641** [comment]
So, what was the fix?
