### ISSUE TITLE
The CSS aren't working properly.

### ISSUE THREAD

**Issue by vinliao** [ChangJoo-Park/vue-editor-js#23]
When I imported the Editor component and show it, it the CSS is a little bit off. This makes the editor hard to see and use. Here's how it looks like. I haven't touched the CSS that's generated by vue cli at all.

![Screenshot from 2019-09-03 15-13-16](https://user-images.githubusercontent.com/34117807/64155751-a2caf080-ce5d-11e9-804d-f401ced2790e.png)

**Comment by ChangJoo-Park** [comment]
Hello @vinliao 
It looks wiered. I'll check it 👍

**Comment by ChangJoo-Park** [comment]
Please use ^2.0.0
