### ISSUE TITLE
Photo Upload Issue

### ISSUE THREAD

**Issue by Xin-Ru** [ChangJoo-Park/vue-editor-js#27]
Hello, 
Thanks for doing this great demo project by Vue. It helps me a lot for work.
But I'm confused about uploading Images, I don't know how to change the backend uploader endpoint url and also the endpoint that provides uploading by Url in Vue.
Really need your help....

**Comment by ChangJoo-Park** [comment]
Thanks @Xin-Ru, I saw error when using image block. (see below)

I'll check this. :) Thank you for reporting
```
Uncaught Error: Url must be a non-empty string
    at s (bundle.js:1)
    at Object.transport (bundle.js:1)
    at t.value (bundle.js:1)
    at t.onSelectFile (bundle.js:32)
    at HTMLDivElement.eval (bundle.js:1)
```

**Comment by ChangJoo-Park** [comment]
@Xin-Ru , Can show me a code when you failed?

**Comment by ChangJoo-Park** [comment]
Please see https://github.com/ChangJoo-Park/vue-editor-js#upload-image
