### ISSUE TITLE
Image plugin

### ISSUE THREAD

**Issue by milanP96** [ChangJoo-Park/vue-editor-js#3]
Image plugin is not working or you corrected it? I see that it is checked in repo

**Comment by ChangJoo-Park** [comment]
@milanP96 sure, If it did not work. please show me your config.

https://github.com/editor-js/image#usage

**Comment by milanP96** [comment]
Hi, @ChangJoo-Park . When I click on "Select an image" nothing is happening

**Comment by milanP96** [comment]
This is my main.js:
```
import Vue from "vue";
import App from "./App.vue";
import router from "./router";
import store from "./store";
import Editor from "vue-editor-js";

Vue.use(Editor);

Vue.config.productionTip = false;

new Vue({
  router,
  store,
  render: h => h(App)
}).$mount("#app");

```

**Comment by milanP96** [comment]
Here is everything like in my case https://codesandbox.io/embed/o7lyqwmvmq

**Comment by yashha** [comment]
I think you need to provide a server that is handling the image.

s. docs - endpoints
https://github.com/editor-js/image#usage
>Required Endpoints for file uploading. 
>Contains 2 fields: 
>byFile - for file uploading 
>byUrl - for uploading by URL

It would be cool not depend on a server in the image component.
To just select and show it. Maybe add it to the json as a base64 encoded string.

**Comment by milanP96** [comment]
@yashha 
Thank you, I try to do it, in general there was an idea to finalize the image plugin and make a gallery, later I will tell you what happens after deploy on server

**Comment by alcovegan** [comment]
My problem with image plugin is getting error when i click on add image icon:
```
Uncaught Error: Url must be a non-empty string
    at s (bundle.js?eb16:1)
    at Object.transport (bundle.js?eb16:1)
    at t.value (bundle.js?eb16:1)
    at t.onSelectFile (bundle.js?eb16:32)
    at HTMLDivElement.eval (bundle.js?eb16:1)
    at t.value (bundle.js?eb16:32)
    at t.value (vue-editor-js.esm.js?1503:3399)
    at e.value (vue-editor-js.esm.js?1503:8008)
    at e.value (vue-editor-js.esm.js?1503:7898)
    at HTMLLIElement.eval (vue-editor-js.esm.js?1503:7950)
```
![error](https://i.imgur.com/VuXiQtf.png)

After that in editor showing up button with Select an Image, and if i click this - i'm getting almost same error. And no dialog for file pick is showing up.
```
Uncaught Error: Url must be a non-empty string
    at s (bundle.js?eb16:1)
    at Object.transport (bundle.js?eb16:1)
    at t.value (bundle.js?eb16:1)
    at t.onSelectFile (bundle.js?eb16:32)
    at HTMLDivElement.eval (bundle.js?eb16:1)
```

I'm passing options for image tool like this:
```
		data() {
			return {
				initData: {},
				editorData: {},
				tools: {
					image: {
						config: {
							endpoints: {
								byFile: "http://localhost:8008/uploadFile",
								byUrl: "http://localhost:8008/uploadFile"
							}
						}
					}
				},
				mode: '',
				name: '',
				slug: '',
				image: null,
				deletedImages: [],
				rest_id: this.$route.params.id
			}
		},
```

Editor wrapper looks like this:
```
			<editor
			:autofocus="true"
			:init-data="initData"
			:customTools="tools"
			ref="editor"
			holder-id="codex-editor"
			save-button-id="save-button"
			@save="saveData"
			@ready="onReady"
			@change="onChange" />
```
I have tried to make just simple html page with EditorJS added by script tags - and everything is ok, when i click to add image - system dialog of picking image showing up. Not sure how to debug where problem is - wrapper or some bug in EditorJS. I have tried to debug it with Vue Devtools, but no luck, i'm not good at debugging :D

Can someone help me with this?

**Comment by assoft** [comment]
Try this...

```
<editor
        ref="editor"
        autofocus
        holder-id="codex-editor"
        save-button-id="save-button"
        :init-data="initData"
        :image="tools.image"
        @save="onSave"
        @ready="onReady"
        @change="onChange"
/>

```

data: 
```
data(){
  return {
    editorData: [],
    initData: {
    },
    tools: {
      image: {
        config: {
          endpoints: {
            byFile: 'http://localhost:3000/uploadByFile', // Your backend file uploader endpoint
            byUrl: 'http://localhost:8008/fetchUrl', // Your endpoint that provides uploading by Url
          }
        }
      }
    }
  }
},
```

**Comment by ChangJoo-Park** [comment]
Hello @alcovegan, I'll check this issue

**Comment by milanP96** [comment]
If somebody can help this. We solved this issue by making our own photo gallery in which the pictures are placed. From there they are also used to view data in editor.js

**Comment by ChangJoo-Park** [comment]
Please see https://github.com/ChangJoo-Park/vue-editor-js#upload-image
sorry @milanP96 , too late 😭
