### ISSUE TITLE
Mismatch in built files

### ISSUE THREAD

**Issue by Loskir** [ChangJoo-Park/vue-editor-js#37]
There is no `config` prop in built file (`vue-editor-js.common.js`)
![image](https://user-images.githubusercontent.com/21295738/71270894-b7c38500-2363-11ea-9fcf-8ca27a37d357.png)

I don't know how does built files work. 

But importing from `/src/` does help
```js
import Editor from 'vue-editor-js/src'
```

Maybe this needs fix

**Comment by Devin345458** [comment]
Bump

**Comment by ErriourRU** [comment]
I think this MUST be fixed... I've the same problem too. @Loskir Thanks for crutch, until no fix from developer.

**Comment by ChangJoo-Park** [comment]
It fixed with ^2.0.0

I remove all useless default plugin settings
