### ISSUE TITLE
How to get the json data

### ISSUE THREAD

**Issue by hkmsadek** [ChangJoo-Park/vue-editor-js#38]
I am trying to get data, i called `this.$refs.editor` but this gives a big obj. Where I can get a actual generated data? Also is it possible to get the row html instead of the json data? 

Thank you.

**Comment by Loskir** [comment]
The data is inside of `save` event. 
```vue
<editor
    ref="editor"
    @save="json = $event"
/>
```
No, it's not possible to get raw HTML data, you should use some renderer listed here
https://github.com/codex-team/editor.js/issues/676#issuecomment-479778254
or write your own.

I'm using the twig one, it's ok.

**Comment by kc980602** [comment]
> The data is inside of `save` event.
> 
> ```
> <editor
>     ref="editor"
>     @save="json = $event"
> />
> ```
> 
> No, it's not possible to get raw HTML data, you should use some renderer listed here
> [codex-team/editor.js#676 (comment)](https://github.com/codex-team/editor.js/issues/676#issuecomment-479778254)
> or write your own.
> 
> I'm using the twig one, it's ok.
so where is the save event triggered? I am accessing the editor component through state is this correct?


```
 @Ref() editor
----------
   this.editor.state.editor.save().then((outputData) => {
                console.log('Article data: ', outputData)
            }).catch((error) => {
                console.log('Saving failed: ', error)
            })
```

**Comment by Loskir** [comment]
As far as I know:
No, it doesn't work with promises
You must assign a listener first. I don't know exactly, somehow like that 
```js
this.editor.state.editor.on('save', (outputData) => {
  console.log('Article data: ', outputData)
})
```

**Comment by kc980602** [comment]
I have another component wrapper for vue-editor-js, and created a function which return a promise.
Then I call this at parent component, seems working🤔

Child
```
        save() {
            return this.editor.state.editor.save().then((outputData) => {
                console.log('outputData', outputData)
               return outputData
            }).catch((error) => {
                console.log('Saving failed: ', error)
                return false
            })
        }
```

Parent
```
  async clickSave() {
            this.outputData = JSON.stringify(await this.contentEditor.save())
        }

```

**Comment by Loskir** [comment]
It's great if it works, didn't think it would
