### ISSUE TITLE
Infinite saving message in console dropping browser

### ISSUE THREAD

**Issue by alcovegan** [ChangJoo-Park/vue-editor-js#4]
Hey there! Thanks for your work with this plugin.

I stuck with some strange behavior of plugin, when i click save button - console is blowing out by infinite Editor.js saving messages, and this is stop only when i drop Chrome tab by dispatcher. I think it is some bug with my code, but it was almost 1:1 copy of example in codesanbox. And then i have tried to hit save button on codesandox and got same console-blow. Then i have tried this in Firefox and Opera - same. Safari is just doesn't work with codesandbox. I'm using MacOS El Capitan 10.11.6.

Error from codesandbox here:

![error](https://i.imgur.com/81GBTAI.png)

On local dev env it is same, except js files names.

Am i doing something totally wrong?

**Comment by alcovegan** [comment]
Ok, i think i got it, i tried example from demo in repository and it's fine.

Sandbox example (and mine) have @save event and save button pointing to one method "save". And we got some recursion here, i think, my head is not working properly in this time :)

**Comment by ChangJoo-Park** [comment]
Hello @alcovegan! It because of codesandbox, webpack HMR.
When you use in production, It maybe not

**Comment by dilvermg** [comment]
using in production and still hanging u.u
