### ISSUE TITLE
Hit enter doesn't work sometime for creating list items

### ISSUE THREAD

**Issue by hkmsadek** [ChangJoo-Park/vue-editor-js#41]
Hi, some time hitting enter make a new list item and sometime it stuck. Most of the time it stuck after adding some contents such image etc. Sometime, when hit enter nothing happens. Any reason why?

**Comment by ChangJoo-Park** [comment]
Can you show me a it happen? I didn't see this issue

**Comment by hkmsadek** [comment]
It doesn't happen everytime, it happens when you add lists after adding some contents images, paragraphs etc.

**Comment by ChangJoo-Park** [comment]
It works on ^2.0.0. you can set every options with this version
