### ISSUE TITLE
Load example data doesn't work

### ISSUE THREAD

**Issue by oronoa** [ChangJoo-Park/vue-editor-js#45]
I see the method being called but the editor doesn't load the new data. 
Seems like the watch is not working as expected.

**Comment by oronoa** [comment]
looks like it's updating but only if I force a rerender it shows the corerect data

**Comment by ChangJoo-Park** [comment]
Please see this \[link\](https://editorjs.io/configuration#passing-saved-data) with vue-editor-js version 2.0.0
