### ISSUE TITLE
"Link" icon

### ISSUE THREAD

**Issue by milanP96** [ChangJoo-Park/vue-editor-js#5]
Hi! Do you know why why icon for link is not showing? 
In devtools button for "like/unlike" looks like this:

```
<button
  type="button"
  class="ce-inline-tool ce-inline-tool--link"
  data-tool="link"
>
  <svg class="icon icon--link" width="15px" height="14px">
    <use
      xmlns:xlink="http://www.w3.org/1999/xlink"
      xlink:href="#link"
    ></use></svg
  ><svg class="icon icon--unlink" width="16px" height="18px">
    <use xmlns:xlink="http://www.w3.org/1999/xlink" xlink:href="#unlink"></use>
  </svg>
</button>
```
Exactly like here(in your example): https://codesandbox.io/embed/o7lyqwmvmq

But in my case, i see "unlink" icon, but "link" icon I do not see. Do you know what is a problem?

**Comment by ChangJoo-Park** [comment]
![2019-04-20 11_33_24-Window](https://user-images.githubusercontent.com/1451365/56450312-275e1c00-6360-11e9-99fe-25fe0c0e58de.png)

Are you saying this?

**Comment by milanP96** [comment]
Hi. Yes, for me, 'link' icon is not showing

**Comment by yashha** [comment]
For me it looks like this but I is showing the icon.
![Screenshot_2019-05-21_17-58-53](https://user-images.githubusercontent.com/4728786/58112022-e8d3af80-7bf2-11e9-8690-e89e13bfaf8b.jpg)

Which browser have you used?

**Comment by yashha** [comment]
Try newest version:
https://codesandbox.io/embed/vue-template-6c3ky

**Comment by ChangJoo-Park** [comment]
You can use directly use link plugin upon ^2.0.0
