### ISSUE TITLE
How could I set logLevel please?

### ISSUE THREAD

**Issue by chenxian352** [ChangJoo-Park/vue-editor-js#51]
Hi. I wanted to mute the launch log

`Editor.js 2.17.0 I'm ready! (ﾉ◕ヮ◕)ﾉ*:･ﾟ✧`

How could I set `logLevel `please?

**Comment by d2phap** [comment]
lots of configs are not applicable in this wrapper

**Comment by ChangJoo-Park** [comment]
You can pass all configs after ^2.0.0 :)
