### ISSUE TITLE
link/unlink not showing

### ISSUE THREAD

**Issue by jvvlimme** [ChangJoo-Park/vue-editor-js#53]
Using nuxt, I'm not seeing the link/unlink option in the inline toolbar
![image](https://user-images.githubusercontent.com/977885/81503352-7405f380-92e3-11ea-8440-6900a5a9aa16.png)

Any ideas on what I'm doing wrong?  I'm using the example nuxt setup

**Comment by ChangJoo-Park** [comment]
Thank you for your issue. I'll try to this.
