### ISSUE TITLE
Config not working

### ISSUE THREAD

**Issue by Joshgallagher** [ChangJoo-Park/vue-editor-js#54]
Passing a config to the editor does not work.

For example, passing this config does not affect the heading.

```
      config: {
        header: {
          config: {
            placeholder: 'Enter a header',
            levels: [2, 3, 4],
            defaultLevel: 3,
          },
        },
      },
```

Instead, all levels are still available and the `defaultLevel` is set to two.

Any ideas?

**Comment by hkmsadek** [comment]
I am having the same issue. Config is not being used :( anyone know the solution?

**Comment by ChangJoo-Park** [comment]
@Joshgallagher , @hkmsadek  please update to ^2.0.0. you can set config on your needs
