### ISSUE TITLE
Version 2.0.1 - TypeError: this.$refs.editor.save is not a function

### ISSUE THREAD

**Issue by daniberv** [ChangJoo-Park/vue-editor-js#61]
How to save the data now? It's not working aftr updating to version 2.0.1

**Comment by h2jose** [comment]
Try this:
`async save(){
    const response = await this.$refs.editor.state.editor.save().then((res)=>res);
    console.log( JSON.stringify(response) )
    ......

},`

**Comment by ken-mike** [comment]
@h2jose After some ten minutes of struggling, I found this issue, the solution on which completely works for me! I appreciate your useful and detailed solution. I think there should be some, like me, who don't have idea how to save (, or in my case, check the constructions of) the edited data, and It would be so nice to add the examples of usages like saving data.

**Comment by ken-mike** [comment]
cc: @ChangJoo-Park
