### ISSUE TITLE
vue-editor-js tools not work in nuxt js

### ISSUE THREAD

**Issue by FarzadMohtasham** [ChangJoo-Park/vue-editor-js#64]
Hi, I'm using vue-editor-js in my nuxt-project and it's ok, But the tools not working!
```javascript
<editor header list code autofocus ref="editor" :initialized="onInitialized"/>
```
How can I solve this problem?

**Comment by kc980602** [comment]
I think you need to npm i the header tool
check this
[https://github.com/ChangJoo-Park/vue-editor-js/blob/master/demo/Demo.vue](https://github.com/ChangJoo-Park/vue-editor-js/blob/master/demo/Demo.vue)

**Comment by nargespms** [comment]
> I think you need to npm i the header tool
> check this
> https://github.com/ChangJoo-Park/vue-editor-js/blob/master/demo/Demo.vue

Hi. This solution is for users who are before version 2.0.0
[https://github.com/ChangJoo-Park/vue-editor-js#for-before-200-version-users](url)

I have the same problem, and dependencies are now in the package.json of version 2.0.2 but still doesn't work!
Do you have any idea?
