### ISSUE TITLE
Do i have to install all components

### ISSUE THREAD

**Issue by kevinwaxi** [ChangJoo-Park/vue-editor-js#66]
seems with your new update i cant seem to find more editor tools such as changing text sizes upload images or other common text editor tools. My question is do i have to install all plugins one by one ?

**Comment by QuyetNguyen95** [comment]
you can try npm install --save vue-editor-js@1.1.1

**Comment by abhishekmatta999** [comment]
why do I have to install every component separately.
In the new version (2.0.2) I always get error while importing editor from vue-editor-js

**Comment by kevinwaxi** [comment]
> you can try npm install --save vue-editor-js@1.1.1

This was so helpful sorry i forgot to reply sooner. Anyway i would be glad if you would point out ways i would also implement the latest version in laravel vuejs application

**Comment by abhishekmatta999** [comment]
> > you can try npm install --save vue-editor-js@1.1.1
> 
> This was so helpful sorry i forgot to reply sooner. Anyway i would be glad if you would point out ways i would also implement the latest version in laravel vuejs application

And how can i insert a custom element inside the editor because i can't find any example related to that. I have also mailed you guys for this query.
