### ISSUE TITLE
Own plugins

### ISSUE THREAD

**Issue by milanP96** [ChangJoo-Park/vue-editor-js#7]
Hi! Can you write a mechanism by which plugins are attached, so that we can write our own ones and not use only those which are on npm?

**Comment by yashha** [comment]
You can pass tools through the customTools attribute
https://github.com/ChangJoo-Park/vue-editor-js#other-props

It will be inserted in the tools property:
https://editorjs.io/the-first-plugin

**Comment by yashha** [comment]
Maybe an example would be an TODO.

**Comment by ChangJoo-Park** [comment]
Thanks @yashha  👍

**Comment by yashha** [comment]
Here is an example:
https://codesandbox.io/embed/vue-template-tvq3s
But I noticed a loop on clicking on save :thinking:

**Comment by ChangJoo-Park** [comment]
Please see this \[link\](https://editorjs.io/the-first-plugin) with vue-editor-js version ^2.0.0
