### ISSUE TITLE
Render created blocks

### ISSUE THREAD

**Issue by thebilljustin** [ChangJoo-Park/vue-editor-js#77]
So i have created blocks and stored these blocks to a database. I want to display it when i fetch it but there is no guide regarding this. How should we approach this?

**Comment by definiteIymaybe** [comment]
For someone who would arrive here wondering the same, one approach can be looked up [here](https://github.com/dnstylish/Vue-EditorJS-Render-View/blob/master/resources/js/components/EditorRenderView.vue). Also, take a look at the [Dynamic Components](https://vuejs.org/v2/guide/components.html#Dynamic-Components) section of Vue docs.
