### ISSUE TITLE
Init data not read by the editor 

### ISSUE THREAD

**Issue by calrloco** [ChangJoo-Park/vue-editor-js#78]
when trying to read the data coming from the db when i pass the value to init-data data the data is not read, do you have any idea why ?

 `                             <editor
                                    v-if="form.initData"
                                    :config="config"
                                    @save="save"
                                    ref="editor"
                                    autofocus
                                    :init-data="form.initData"
                                />`

data() {
        return {
            form: {
                title: this.artilceTitle,
                body: null,
                tags: this.selectedTag,
                category: this.selectedCategory,
                files: null,
                initData:JSON.parse(JSON.stringify(this.initData)),
            },

**Comment by calrloco** [comment]
j

**Comment by kevinwaxi** [comment]
did you solve this
