### ISSUE TITLE
How to update the editor data dynamically? (axios)

### ISSUE THREAD

**Issue by greenphp** [ChangJoo-Park/vue-editor-js#8]
Hi,

I integrated the vue-editor-js in my vue project and it works fine. Saving the data into my database works.

Unfortunately I can't find a way to dynamically update the <editor> component data. 

**How to update the editor data from my data retreived from the database?**

```
<template>
    <editor :init-data="articleBlocks" />
</template>
    
<script>
export default {
    data() {
        return {
            articleBlocks: {}
        }
    },
    methods: {
        onListEdit(listId) {
            axios.get('/api/lists/' + listId)
                .then(response => {
                    let item = response.data;
                    this.articleBlocks = JSON.parse(item.articleBlocks);
                })
            ;
        }
    }
}
</script>
```

**Comment by ChangJoo-Park** [comment]
have you tried `this.$set('articleBlocks', JSON.parse(item.articleBlocks));` ?

**Comment by ChangJoo-Park** [comment]
More information, 
when you set data using `=`, Vue didn't know it need observers for Object

**Comment by greenphp** [comment]
Hi,

thank you for your fast answer. I tried to update my code it but now receive an Vue warning and it still doesn't work. Can you give me another hint? ;) 

```
onListEdit(listId) {
    let vm = this;
    axios.get('/api/lists/' + listId)
        .then(response => {
            let item = response.data;
                vm.$set('articleBlocks', JSON.parse(item.articleBlocks));
            });
    }
```

Error:

```
[Vue warn]: Cannot set reactive property on undefined, null, or primitive value: articleBlocks

TaskListForm.vue:255 TypeError: Cannot use 'in' operator to search for '#<Object>' in articleBlocks
    at VueComponent.set [as $set] 
```

**Comment by ChangJoo-Park** [comment]
is item.articleBlocks exists?

**Comment by greenphp** [comment]
Yes, it exisits. It's returned from the API. If I console.log() it just the line before, it looks perfect.

The plain data looks like this.

`{"time":1558094653932,"blocks":[{"type":"paragraph","data":{"text":"Some content"}}],"version":"2.12.3"}`

**Comment by ChangJoo-Park** [comment]
In your codes, you are using `item.articleBlocks`.
but You must use `item.blocks` .
please check this part :)

**Comment by greenphp** [comment]
Hi,

I tried this too. Unfortunately I can't get it to work, and I don't know why. That's really a pity, because saving works just fine.

Looks like :init-data requires an object (I just pass an empty object by now), but the "blocks" part of the returned data is an array of block objects. This isn't compatible. It's not defined what " :init-data" is, and how to initialize / update it correctly. I've done this with try and error. 

Maybe it's possible for you to create an example, how the loading / saving of data works.

**Comment by ChangJoo-Park** [comment]
Hi @geenphp , I want to solve your issue. Please give me a example project. :sob:

It is wiered.

**Comment by greenphp** [comment]
Hi, I created a new component just to test it. And it also doesn't work.

Can you please try to fix this example? Guess there is a small thing I totally miss.

```
<template>
    <div>
        <editor
            :autofocus="true"
            :init-data="editorData"
            ref="editor"
            @save="onSaveEditorJs"
        />
        <v-btn
            type="submit"
            @click.prevent="onSubmit"
        >Save</v-btn>
    </div>
</template>

<script>

    export default {
        data() {
            return {
                editorData: {}
            }
        },
        mounted() {
            this.loadEditorData();
        },
        methods: {
            loadEditorData() {
                this.$set(
                    this,
                    'editorData',
                    JSON.parse('{"time":1558356864490,"blocks":[{"type":"paragraph","data":{"text":"First text"}},{"type":"paragraph","data":{"text":"Second text"}}],"version":"2.12.3"}'
                ));
            },
            onSubmit() {
                this.$refs.editor.save();
            },
            onSaveEditorJs: (editorData) => {
                console.log(JSON.stringify(editorData));
            }
        }
    }

</script>

```

**Comment by marthings** [comment]
Wow im trying this as well :D Having exact the same problem

**Comment by yashha** [comment]
I think we would have to add a load/render function to the editor:
https://editorjs.io/blocks#render
